# Generated by Django 4.2.6 on 2023-10-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_user_id_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_info',
        ),
    ]
