# Generated by Django 4.2.6 on 2023-11-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_user_user_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
