# Generated by Django 4.2.6 on 2023-11-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
